### PR TITLE
feat: cache installs

### PR DESCRIPTION
**Pull request by dudymas**
## what

- use github's cache/restore and cache/save workflows

## why

- Some end users hit API limits on app installs
- Constantly reinstalling is a waste of compute, net, and IO

## references:

- [actions/cache](https://github.com/actions/cache)

### CODE REVIEW

**Review by goruha — CHANGES_REQUESTED** [review]
The logic using cache should be inside actions that perform installation.

for example inside
```
cloudpoose/setup-atmos
```

**Comment by hans-d** [comment]
@dudymas can you resolve the merge conflict?

**Comment by dudymas** [comment]
> @dudymas can you resolve the merge conflict?

@hans-d updated. @goruha , I forget if this is still something we want in 'terraform-plan', or if this was fixed by the atmos install action.

**Comment by goruha** [comment]
@dudymas thanks for PR.
I think we should split caches `.terraform` and `cli` tools cache.

Check this #83

**Pull request closed without merging**
